version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
    opendlv-logic-cfsd18-sensation-slam:
        image: "graphslam:graphslamv0.0.2"
        network_mode: "host"
        ipc: host
        command: "opendlv-logic-cfsd18-sensation-slam --cid=${CID} --id=120 --detectConeId=116 --estimationId=114 --gatheringTimeMs=20 --sameConeThreshold=1.2 --refLatitude=48.123141 --refLongitude=12.34534 --timeBetweenKeyframes=500 --coneMappingThreshold=50 --conesPerPacket=20"
#    odcockpit:
#        image: ${IMAGE}
#        network_mode: host
#        environment:
#        - DISPLAY=$DISPLAY
#        volumes:
#        - /tmp/.X11-unix:/tmp/.X11-unix
#        - .:/opt/opendlv.data
#        - ~/Recordings:/opt/Recordings
#        ipc: host
#        user: odv
#        depends_on:
#            - odsupercomponent
#        command: "/opt/od4/bin/odcockpit --cid=${CID}"
    #Cone detection
    cfsd18-sensation-attention:
        image: "seresearch/opendlv-cfsd18-on-opendlv-lynx-on-opendlv-on-opendlv-core-on-opendavinci-on-base-dev:latest"
        network_mode: "host"
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.cfsd18/bin/opendlv-logic-cfsd18-sensation-attention --cid=${CID} --verbose=1 --id=1"
    #proxy-velodyne16
    velodyne16:
        image: ${IMAGE}
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        ipc: host
        user: odv
        working_dir: "/opt/opendlv.data"
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-velodyne16 --cid=${CID}"
